### ISSUE TITLE
Add colors to New Tab container menu

### ISSUE THREAD

**Issue by Smile4ever** [eoger/tabcenter-redux#70] opened 2017-06-20 10:15 UTC
Currently, the icons are black and white instead of their container color. My custom container doesn't even have an icon. I'm talking about the menu you see when you long press the "New Tab" button.

**Comment by eoger** [comment] 2017-06-20 14:48
Try setting svg.context-properties.content.enabled to true in about:config.

**Comment by eoger** [comment] 2017-06-21 04:37
However, custom containers not having icon is a real issue. Let's see what we can do here.

**Comment by Smile4ever** [comment] 2017-06-21 04:46
> Try setting svg.context-properties.content.enabled to true in about:config.

That works for adding colors 👍

**Comment by eoger** [comment] 2017-06-23 00:53
These 2 problems should be fixed for good for everyone (no need to flip the pref) by https://github.com/eoger/tabcenter-redux/commit/d77a6fd80531a2a386e08c53070f594ecffd3222 and https://github.com/eoger/tabcenter-redux/commit/08ebf712adde369f804d6af8aac2db59c4dceaa9.

Feel free to re-open if the problem is not resolved for you.

**Closed by eoger** 2017-06-23 00:53 UTC
Labels: A-P2, B-actionnable
