### ISSUE TITLE
Add option to hide horizontal tabs

### ISSUE THREAD

**Issue by Vityacv** [eoger/tabcenter-redux#175] opened 2017-09-29 10:24 UTC
Horizontal tabs are useless (at least for me) if you have added "Tabs" sidebar.

**Comment by Vityacv** [comment] 2017-09-29 11:06
Maybe it will be possible with this api? https://bugzilla.mozilla.org/show_bug.cgi?id=1384515

**Comment by Smile4ever** [comment] 2017-09-29 14:06
You are looking for https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by benmullins** [comment] 2017-09-30 05:28
Yes, this is currently impossible to achieve _automatically_ with the WebExtensions API, but until this changes it's possible to remove the native tab bar by adding this to userChrome.css:

```
#TabsToolbar { visibility: collapse; }
```

**Comment by bam80** [comment] 2017-10-03 14:25
@benmullins 
>`#TabsToolbar { visibility: collapse; }`

Should it work if filling in "Custom stylesheet" Advanced Setting? https://github.com/eoger/tabcenter-redux/issues/151
Seems do not works for me in Firefox 56.0

**Comment by Smile4ever** [comment] 2017-10-03 14:40
You need to put

    #TabsToolbar { visibility: collapse; }

in userChrome.css. This is something Firefox-specific that Tab Center Redux cannot do due to the current technical limitations. The CSS option in Tab Center Redux allows you to change Tab Center Redux, not Firefox itself.

**Comment by eoger** [comment] 2017-10-05 01:08
Duplicate of #15

**Closed by eoger** 2017-10-05 01:08 UTC
