### ISSUE TITLE
Add Undo Close Tab/Duplicate Tab to the context menu 

### ISSUE THREAD

**Issue by mathearts** [eoger/tabcenter-redux#147] opened 2017-08-16 18:35 UTC
Is it possible to add items such as Duplicate tab and Undo last tab to the right-click menu? Or can I add them myself using a pull request? Thanks!

**Comment by eoger** [comment] 2017-08-18 00:49
Duplicate of #66
I would accept a PR for Undo! https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions/getRecentlyClosed

**Comment by Smile4ever** [comment] 2017-08-21 18:24
Firefox uses the "Undo Close Tab" terminology. I suggest we use the same.

**Comment by eoger** [comment] 2017-09-09 20:36
Duplicate Tab is now in available in Firefox, let's make it available in Tab Center Redux.
[Here's the function to call](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/duplicate) if someone wants to try their hand at it.

**Closed** 2017-10-05 02:34 UTC
Labels: A-P2, B-actionnable
