### ISSUE TITLE
show/hide vertical tabs on hotkey

### ISSUE THREAD

**Issue by atommixz** [eoger/tabcenter-redux#254] opened 2017-11-16 11:52 UTC
TST used F1 for this option. I like it. Useful for me. Can u do the same?

**Comment by EvanHahn** [comment] 2017-11-17 15:30
I'm not sure if it's documented, but Ctrl+Shift+O (or ⌘+Shift+O on macOS) opens and closes the sidebar for me.

**Comment by gooddadmike** [comment] 2017-11-17 21:51
This should be indicated on the sidebar and also documented in the options. Looking at the manifest also appears the Ctrl Shift L highlights the tab search. Doesn't work for me though.

**Comment by eoger** [comment] 2017-11-18 03:42
Duplicate of https://github.com/eoger/tabcenter-redux/issues/131, I'll update the add-on description to make it clearer.

**Closed by eoger** 2017-11-18 03:42 UTC
