### ISSUE TITLE
Open new tabs at the top of the list

### ISSUE THREAD

**Issue by kumar303** [eoger/tabcenter-redux#144] opened 2017-08-15 16:19 UTC
Just like Tab Center, there should be a preference to make new tabs open at the top of the list, not the bottom. This is crucial for when you have a long list of tabs.

**Comment by Keith94** [comment] 2017-08-15 16:21
Duplicate of #5.

**Comment by kumar303** [comment] 2017-08-15 17:55
For now, I am able to use a separate add-on to achieve the same functionality: https://github.com/autonome/Always-Right

**Comment by eoger** [comment] 2017-08-18 00:51
Thanks for spotting the duplicate. Closing.

**Closed by eoger** 2017-08-18 00:51 UTC
