### ISSUE TITLE
Better search & keyboard support

### ISSUE THREAD

**Issue by bisho** [eoger/tabcenter-redux#173] opened 2017-09-28 17:30 UTC
Having a hotkey for the search, better yet, focus on the search box could be set automatically when opening the extension.

And after search, allow up/down arrays to select the tab + enter to switch.

This extension is mean for users that manage a lot of tabs, and for that proper keyboard support is needed, not forcing to reach for the mouse. A good example of this is the "Quick Tabs" extension for chrome. Right now that extension is the only thing that ties me to chrome.

**Comment by eoger** [comment] 2017-11-14 03:03
Duplicate of https://github.com/eoger/tabcenter-redux/issues/216

**Closed by eoger** 2017-11-14 03:03 UTC
