### ISSUE TITLE
how to use original context menu? FoxyTab support

### ISSUE THREAD

**Issue by whoamin** [eoger/tabcenter-redux#371] opened 2018-06-10 22:15 UTC
I think tabcenter-redux uses it's own context menu. So I can't use FoxyTab because of this.

https://addons.mozilla.org/en/firefox/addon/foxytab/

**Comment by Keith94** [comment] 2018-06-10 22:29
It's not supported by Firefox yet: #6

**Comment by Smile4ever** [comment] 2018-06-29 10:44
@eoger You can close this one as a duplicate of bug 6.

**Closed** 2018-07-02 23:50 UTC
