### ISSUE TITLE
'focus-searchbox' keyboard shortcut does not focus the search box

### ISSUE THREAD

**Issue by mikuslusens** [eoger/tabcenter-redux#216] opened 2017-10-22 22:50 UTC
Knowing that an extension's sidebar actions are defined in the 'manifest.json' file, I looked in the extension's 'manifest.json' file to see if any keyboard shortcuts are defined. I noticed the extension's sidebar has two keyboard shortcuts listed- one, it seems, for showing the sidebar and one for, judging by the name, focusing the sidebar's search box. The shortcut for showing the sidebar (Ctrl+Shift+O) works as expected, but the other one (Ctrl+Shift+L) doesn't, at least on my system. Nothing happens after I press it. This shortcut is not reserved by Firefox afaik. Can anything be done about this? 

Firefox version: 56.0 64-bit
OS: Windows 7 64-bit

**Comment by eoger** [comment] 2017-10-24 01:08
I investigated that bug a little bit, and it seems that this shortcut only works in about:debugging.
Using the mozregression tool, I determined that this bug has always been around.
You might try your luck and open a Firefox bug on Bugzilla, but maybe it is intended behavior?

**Comment by mikuslusens** [comment] 2017-10-24 06:00
Oh, alright then. I figured there would be some other limitations in place. I'm guessing the 'focus-searchbox' sidebar action is one of a set of available sidebar actions? In that case opening a bug report is probably the only option, yes. That might also give an answer as to whether or not it's intended behavior.

**Comment by eoger** [comment] 2017-11-18 20:33
Closing since I removed the option, I hope I'll be able to bring it back at some point.

**Closed by eoger** 2017-11-18 20:33 UTC
Labels: A-P2, C-bug
