### ISSUE TITLE
[0.4.2] Invisible tab after closing last tab in the window with browser.tabs.closeWindowWithLastTab false

### ISSUE THREAD

**Issue by SXZ1** [eoger/tabcenter-redux#203] opened 2017-10-19 09:48 UTC
Hello!
STR: Create new profile, install TCR0.4.2 from AMO, open Tab Center Redux sidebar, open new tab, go to about:config, set 
browser.tabs.closeWindowWithLastTab false
Open new window, press Ctrl-W

ER: One tab in the sidebar
AR: No tabs in the sidebar, sidebar is completely empty

**Comment by eoger** [comment] 2017-10-19 16:44
Duplicate of https://github.com/eoger/tabcenter-redux/issues/165

**Closed by eoger** 2017-10-19 16:44 UTC
