### ISSUE TITLE
Add an option to always show scrollbar

### ISSUE THREAD

**Issue by upsuper** [eoger/tabcenter-redux#129] opened 2017-08-07 04:56 UTC
It is sometimes annoying that when you are closing multiple tabs, and the scrollbar suddenly disappears because the number of tabs is low enough to not show that.

Alternatively, it may also be helpful if the scrollbar can be displayed at the left side of the panel.

**Comment by mlissner** [comment] 2017-08-08 20:52
Can you elaborate about why this is annoying? Does it move the icons in a bad way? Maybe that can be addressed via a more minimal approach than showing the scrollbar all the time?

**Comment by mathearts** [comment] 2017-08-12 10:44
On the other side, is it possible to completely hide the scrollbar using userChrome.css?

**Comment by eoger** [comment] 2017-08-18 00:55
This looks like feature creep to me, however I might introduce a custom CSS thingy in the future which would allow you to do that.

**Comment by eoger** [comment] 2017-08-19 18:06
Duplicate of https://github.com/eoger/tabcenter-redux/issues/151

**Closed by eoger** 2017-08-19 18:06 UTC
