### ISSUE TITLE
Add option to hide top bar

### ISSUE THREAD

**Issue by Smile4ever** [eoger/tabcenter-redux#150] opened 2017-08-19 11:57 UTC
Add an option which hides the top bar. What I call the top bar contains the new tab button, the settings button and the search box.

I rarely use the top bar and I could use this space to show one more tab.

**Comment by eoger** [comment] 2017-08-19 18:06
Duplicate of https://github.com/eoger/tabcenter-redux/issues/151

**Closed by eoger** 2017-08-19 18:06 UTC
