### ISSUE TITLE
Work out if we're effected by bug 1398272

### ISSUE THREAD

**Issue by thomcc** [eoger/tabcenter-redux#312] opened 2018-02-13 16:45 UTC
It seems likely, but I don't fully understand the issue. https://bugzilla.mozilla.org/show_bug.cgi?id=1398272

There's a helpful library to work around the issue that doesn't appear to be much work to integrate https://github.com/piroor/webextensions-lib-tab-id-fixer

**Comment by eoger** [comment] 2018-03-30 02:42
Duplicate of https://github.com/eoger/tabcenter-redux/issues/325, closing! Seems like they fixed the bug 👍

**Closed by eoger** 2018-03-30 02:42 UTC
