### ISSUE TITLE
Support Tab Hiding

### ISSUE THREAD

**Issue by kah0922** [eoger/tabcenter-redux#296] opened 2018-01-21 06:02 UTC
Initial support for tab hiding [has landed as of the 1-19 build of Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1423725). Currently, only [Conex](https://addons.mozilla.org/en-US/firefox/addon/conex/) has enabled support for this.

Currently, Tab Center Redux will show all tabs regardless of whether they are hidden (via Conex or when other Tab addons add support) or not.

**Comment by eoger** [comment] 2018-02-01 07:01
Yes, this is definitely needed.  
Things to do on the top of my head:
- In the tabs.query() calls, specify `hidden: true` if it is supported. If not we'll have to do the filtering later.
https://github.com/eoger/tabcenter-redux/blob/53c279f3cafb889b11f410d4522a9808d58f1e4e/src/tablist.js#L450
- Verify that tabs.onUpdated() is called with `changeInfo.hidden`.
https://github.com/eoger/tabcenter-redux/blob/53c279f3cafb889b11f410d4522a9808d58f1e4e/src/tablist.js#L113
- Removing the tab element from the DOM if it's hidden is probably the best solution perf-wise, but it might be a bit more work to implement.

**Comment by thomcc** [comment] 2018-02-11 12:49
Is issue this just to show/hide these tabs in the sidebar (e.g. to behave well in the face of another extension that uses this api), or is it to add the ability to hide tabs in some manner

**Comment by neomodern** [comment] 2018-02-12 13:53
I think the former as the extension author has said [they're not planning to add Tab Groups](https://github.com/eoger/tabcenter-redux/issues/36) right now, and this is likely to be the main use of the API.

**Comment by Smile4ever** [comment] 2018-02-12 13:57
A context menu item to hide the a tab from the sidebar using the WebExtensions APIs would probably be needed as well.

**Comment by gee-forr** [comment] 2018-02-28 09:33
I was wondering... would a good first pass of this functionality be to just merely only show non-hidden tabs instead of implemented full show/hide functionality?

I suspect that anyone currently hiding tabs are doing so via Conex, and will continue to do so via Conex & co, and really just want TabCenter redux for the sidebar.

**Comment by eoger** [comment] 2018-03-11 07:11
I just pushed a [commit](https://github.com/eoger/tabcenter-redux/commit/ebcdf585b52b55600d13977f56b2799546f2c438) in the [dev branch](https://github.com/eoger/tabcenter-redux/tree/dev) that makes Tab Center aware of the `Tab.hidden` attribute.
I didn't add any sort of "Hide tab" button, so you'll need another extension such as [Conex](https://addons.mozilla.org/en-US/firefox/addon/conex/) to hide them for you.

I went for the optimized implementation, which means that I had to refactor the very core of the extension (tabs positioning), but that change was long due anyway and it should bring performance improvements.
However, I'm pretty concerned about potential regressions from this patch, which is why I'd like you to play with it it 😀
Here are the things to test in particular:
  - Tab hiding (duh)
  - Anything that implicates moving around tabs (drag-and-drop, move to new window, pin/unpin etc.)

So far I ironed out everything that I could see, but I might have missed stuff.
Thanks!

**Comment by gee-forr** [comment] 2018-03-11 07:18
@eoger - thank you so much for this! How would I go about building this extension to use locally on my machine?

**Comment by eoger** [comment] 2018-03-11 16:19
- Download the branch [as a zip file](https://github.com/eoger/tabcenter-redux/archive/dev.zip).
- Open `about:debugging` in Nightly (or if using Beta make sure the pref `dom.moduleScripts.enabled` is true).
- Press the "Load Temporary Addon" button, and open the `manifest.json` file in the extracted zip.

**Comment by gee-forr** [comment] 2018-03-11 16:33
Awesome - thanks. I'm using it as we speak. And so far so good. I'll report back on this thread if I find any issues.

**Comment by gee-forr** [comment] 2018-03-12 09:29
Hi,

Some quick feedback - I've been using it for about 12 hours with about 150 tabs across 8 tab groups, and everything is going great. Haven't noticed any issues.

Nice work, and thank you so much once again, I'm finally getting Firefox back to my pre-57 state. This extension + conex plays a huge part in that. I really appreciate the work you've done.

**Comment by eoger** [comment] 2018-03-13 01:07
Thanks @gee-forr, appreciated!

I found a regression:
Start state: Tabs [A, B, C, D].
Close tab B.
Switch to tab C and Ctrl+Click a link.
The new Tab will open in the wrong position. I think this is because I'm not shifting the index numbers in _remove(). I'll fix that when I get some time.

**Comment by Keith94** [comment] 2018-03-13 01:07
After quick test: 'Close Tabs Underneath' only closes the last tab in the list. Can you confirm ?

**Comment by eoger** [comment] 2018-03-13 01:38
@Keith94 I wonder if you have these issues because the order is messed up by the bug I describe in https://github.com/eoger/tabcenter-redux/issues/296#issuecomment-372512301.
Can you still reproduce when "re-syncing" the tabs state by reloading the temporary extension?

**Comment by Keith94** [comment] 2018-03-13 01:54
I can still reproduce. Downloaded the dev build today. Also hit "reload" in about:debugging.

**Comment by eoger** [comment] 2018-03-13 02:27
I couldn't reproduce the "Close Tabs underneath" problem.
- Are you using any tab-hidding extension?
- If it's not too much work, could you post a step-by-step STR?

**Comment by Keith94** [comment] 2018-03-13 02:45
Yes, I am using - https://addons.mozilla.org/addon/experimental-simple-tab-groups

Sorry, I don't know the exact steps - don't have time to test now.
1. Open 4+ tabs
2. Middle-click new tab button a few times (position is buggy)
3. Close tabs underneath

![2018-03-12_19-40-42](https://user-images.githubusercontent.com/5490615/37319749-9d5748bc-262d-11e8-8228-149dd4ad6827.gif)

**Comment by eoger** [comment] 2018-03-28 04:49
Apologies for the delay, I've been pretty busy lately. Thanks a lot for the reports.
The `dev` branch has been updated with the work I've been doing these past days.
The good news is that I am way more confident now regarding potential regressions, because we finally have tests!
Would you mind giving it a try again? (see https://github.com/eoger/tabcenter-redux/issues/296#issuecomment-372127510 for instructions).

**Comment by gee-forr** [comment] 2018-03-28 05:48
Excellent news! I'm running the latest revision right now :) I'll post some feedback if I find any issues.

**Comment by gee-forr** [comment] 2018-03-29 12:03
Hi @eoger - I've been running this version for a day or two now, and haven't noticed any of the issues from the previous version with tabs being shown out of order. This version looks to be very well put together - thanks :)

**Comment by Keith94** [comment] 2018-03-29 22:58
@eoger The previous issue seems to have been fixed.

Another thing, the throbber animations are no longer synced with each other now.

**Comment by eoger** [comment] 2018-03-30 02:33
Merged in https://github.com/eoger/tabcenter-redux/commit/ef7b368ca596c7bb61dcc967508c9212af35076d, thanks everyone!  
This work demanded a big/risky refactor, but it was definitely worth the trouble since it will allow us to make other improvements that were not even possible or very hard to implement in the past.

Feel free to open new issues if you notice something wrong once it goes live.

**Closed by eoger** 2018-03-30 02:33 UTC
Labels: A-P1, B-actionnable

**Comment by gee-forr** [comment] 2018-03-30 09:59
Fantastic news! When will you release to AOM?
