### ISSUE TITLE
Hide with one Tab

### ISSUE THREAD

**Issue by qoheniac** [eoger/tabcenter-redux#289] opened 2018-01-03 16:54 UTC
Is it possible (maybe via css) to hide the side bar if there's only one tab?

**Comment by Smile4ever** [comment] 2018-01-03 18:51
Duplicate of https://github.com/eoger/tabcenter-redux/issues/168

**Closed** 2018-02-01 07:11 UTC

**Comment by Keith94** [comment] 2018-04-07 05:16
I added a workaround here: https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-Tweaks#hide-sidebar-with-only-one-tab-open
