### ISSUE TITLE
When dragging/dropping tabs, it always goes above/below the tab being hovered on.

### ISSUE THREAD

**Issue by mparkms** [eoger/tabcenter-redux#105] opened 2017-07-08 00:06 UTC
When dragging/dropping tabs to rearrange them, it appears that tabs are always placed above the tab the mouse is over when the drop happens if dragging upwards from its original position, and below if dragging downwards from its original position.

I think the expected behaviour should be that if the mouse is on the lower half of a tab, the tab being dragged should be placed below that tab, and if it's on the upper half, it should be placed above.  The current behaviour leads to tabs being placed in unintended locations, especially because it's not always obvious which tab the mouse is over. An indicator to show where the tab will be placed would help, but I think this behaviour should be fixed as well.

I'm not sure if I explained this well so please ask questions if you're not clear.

**Comment by eoger** [comment] 2017-07-24 00:16
I believe this is how the previous edition of Tab Center did things.
However I would not be against a PR that changes that behavior, assuming it wouldn't add too much complexity to the code.

**Comment by eoger** [comment] 2017-08-18 01:04
Duplicate of #141

**Closed by eoger** 2017-08-18 01:04 UTC
