### ISSUE TITLE
Top tabs should be hidden

### ISSUE THREAD

**Issue by karlcow** [eoger/tabcenter-redux#88] opened 2017-06-22 23:41 UTC
1. Install Tab Center Redux
2. Have the Tab Center vertical bar.

Expected: Top tabs are not in view anymore

Actual: Top tabs are still visible.

Using 56.0a1 (2017-06-21) (64-bit) on macOS

**Comment by Keith94** [comment] 2017-06-22 23:42
Duplicate of #15

**Closed** 2017-06-23 00:54 UTC
